name: Build Win64

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019

    env:
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/.vcpkg-bc

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "vcpkg: setup binary cache"
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
          path: |
            .vcpkg-bc
          restore-keys: |
            ${{ runner.os }}-vcpkg-
            ${{ runner.os }}-

      - name: Create vcpkg binary cache folder
        shell: bash
        run: mkdir -p .vcpkg-bc

      - name: Bootstrap vcpkg
        shell: cmd
        run: .\vcpkg\bootstrap-vcpkg.bat

      - name: Build localisation files
        run: bash build-po.sh
        shell: bash

      - name: "CMake: Configure"
        shell: cmd
        run: cmake --preset win64-2019-rel

      - name: "CMake: Build"
        shell: cmd
        run: cmake --build --preset win64-2019-rel

      - uses: actions/upload-artifact@v3
        with:
          name: win64-build
          path: |
            build/win64-2019-rel/um-desktop/Release/
      - uses: actions/upload-artifact@v3
        with:
          name: locale
          path: |
            build/win64-2019-rel/**/*.mo
